-- ============================================================
-- SCRIPT DI CREAZIONE TABELLE MANCANTI (COMPATIBILE BIGINT)
-- Esegui questo nel SQL Editor di Supabase
-- ============================================================

-- Nota: Abbiamo rilevato che le tue tabelle 'posts' e 'users' 
-- usano ID di tipo BIGINT o simili, non UUID.
-- Questo script crea le tabelle con i tipi corretti.

-- 1. Creazione tabella post_comments
CREATE TABLE IF NOT EXISTS public.post_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Assicuriamoci che tutte le tabelle abbiano RLS disabilitato
ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.post_interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.post_comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.chat_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.soul_links DISABLE ROW LEVEL SECURITY;

-- 4. Permessi completi
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.posts TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.post_interactions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.post_comments TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.chat_requests TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.interactions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.soul_links TO anon, authenticated, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
