-- SCRIPT DI CREAZIONE TABELLA BANNER GLOBALI
-- Esegui questo nel SQL Editor di Supabase

CREATE TABLE IF NOT EXISTS public.banner_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    name TEXT,
    photo_url TEXT,
    city TEXT,
    dob TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Disabilita RLS per consentire letture/scritture pubbliche
ALTER TABLE IF EXISTS public.banner_messages DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.banner_messages TO anon, authenticated, service_role;
